{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE FunctionalDependencies #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE TemplateHaskell #-}
-- | Optics generated by makeLenses and friends inherit field/constructor
-- Haddocks (#614). Assertions live in "T614Check": getDoc cannot see docs
-- attached by putDoc in the same module. Compiled with @-haddock@.
module T614 where

import Control.Lens

-- makeLenses: documented and undocumented fields
data Melon = Melon
  { _melonWeight       :: Int -- ^ Weight in grams.
  , _melonUndocumented :: Char
  }
makeLenses ''Melon

-- makeClassy: per-field class methods
data Cabin = Cabin
  { _cabinBunks :: Int  -- ^ Number of bunks.
  , _cabinHeat  :: Bool -- ^ Whether the cabin is heated.
  }
makeClassy ''Cabin

-- makeFields: shared Has* class methods must not inherit
data Yurt = Yurt
  { _yurtArea :: Double -- ^ Floor area in square metres.
  }
makeFields ''Yurt

-- fields merged into one traversal must not inherit
data Twin = Twin
  { _twinA :: Int -- ^ First coordinate.
  , _twinB :: Int -- ^ Second coordinate.
  }
makeLensesFor [("_twinA", "twins"), ("_twinB", "twins")] ''Twin

-- makePrisms: documented and undocumented constructors
data Shape
  = Circle Double      -- ^ A circle with a radius.
  | Rect Double Double -- ^ A rectangle.
  | UndocShape
makePrisms ''Shape

-- makePrisms, single-constructor Iso special case
newtype Temp
  = MkTemp Double -- ^ A temperature in Celsius.
makePrisms ''Temp

-- makeClassyPrisms: class method signatures
data Signal
  = Red   -- ^ Stop.
  | Green -- ^ Go.
makeClassyPrisms ''Signal

-- no-clobber: the handwritten documentation below must survive
data Pear = Pear
  { _pearRipeness :: Int -- ^ Field documentation that must not win.
  }

makeLensesWith (lensRules & generateSignatures .~ False) ''Pear

-- | Handwritten documentation that must survive.
pearRipeness :: Lens' Pear Int
