#! /bin/bash

g() { git grep --basic-regexp "$@" src | wc -l ; }
cd "$(git rev-parse --show-toplevel)"

unsafe="$(g -e '\(#\.\|\.#\)' --and --not \
	\( -e INLINE --or -e '^\s*(\s*\(#\.\|\.#\)\s*)' \))"
doc="$(g -e '--\s\+>>>\s\+[^:]' --and --not -e '--\s\+>>>\s\+\(import\|let\)' \
	--or -e '--\s\+>>>\s\+let\s\+.*\<in\>')"
ops="$(g '^(.\+)\s*::')"
mod="$(find src -name '*.hs' | wc -l)"

echo "unsafeCoerces: $unsafe | doctests: $doc | operators: $ops | modules: $mod"

